### ISSUE TITLE
Version request 

### ISSUE THREAD

**Issue by rahvis** [M-Soundouss/density_based_conformal_prediction#1]
Please note that this is not an ISSUE. 

I am requesting to share the versions used for the libraries:

> - Keras
> - Tensorflow
> - numpy
> - pandas
> - sklearn
> - matplotlib

**Comment by M-Soundouss** [comment]
Hello, 
Thank you for your comment. I just added a requirements file. 
Have a nice day!
Kind regards,
Soundouss

**Comment by rahvis** [comment]
Thanks you so much :)
